'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Search

    '''<summary>
    '''frmSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearch As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SearchHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchHeader As Global.PPC.TrackingHeader

    '''<summary>
    '''searchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''searchUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblSearchTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchTerm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''exportToExcelTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents exportToExcelTop As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''searchTabContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchTabContainer As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tabpanelMerged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabpanelMerged As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblMerged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMerged As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedLegend1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedLegend1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedLegend2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedLegend2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedLegend3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedLegend3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedSearch As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridMergedMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tabpanelPhonetic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabpanelPhonetic As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblPhonetic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhonetic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticLegend1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticLegend1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticLegend2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticLegend2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticLegend3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticLegend3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticSearch As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridPhoneticMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tabpanelOrthographic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabpanelOrthographic As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblOrthographic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrthographic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicLegend1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicLegend1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicLegend2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicLegend2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicLegend3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicLegend3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicSearch As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridOrthographicMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tabpanelText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabpanelText As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridTextHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridTextSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextSearch As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridTextMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tabPanelAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabPanelAll As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gridMergedHeaderAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedHeaderAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedLegend1All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedLegend1All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedLegend2All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedLegend2All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedLegend3All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedLegend3All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedPanelAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedPanelAll As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gridMergedSearchAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedSearchAll As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridMergedMessageAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedMessageAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gridPhoneticHeaderAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticHeaderAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticLegend1All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticLegend1All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticLegend2All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticLegend2All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticLegend3All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticLegend3All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticPanelAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticPanelAll As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gridPhoneticSearchAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticSearchAll As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridPhoneticMessageAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticMessageAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gridOrthographicHeaderAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicHeaderAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicLegend1All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicLegend1All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicLegend2All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicLegend2All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicLegend3All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicLegend3All As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicPanelAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicPanelAll As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gridOrthographicSearchAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicSearchAll As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridOrthographicMessageAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicMessageAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridTextAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gridTextHeaderAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextHeaderAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridTextPanelAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextPanelAll As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gridTextSearchAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextSearchAll As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridTextMessageAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextMessageAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''exportToExcelBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents exportToExcelBottom As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''searchRunning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchRunning As Global.System.Web.UI.WebControls.PlaceHolder
End Class
