'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DirectSearch

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCandidateDrug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCandidateDrug As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCandidateDrug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCandidateDrug As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblComparatorDrug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComparatorDrug As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComparatorDrug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComparatorDrug As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SearchReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchReset As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''SearchSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchSubmit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblValidate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValidate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divScoreResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divScoreResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCombinedScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCombinedScore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCombinedScoreVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCombinedScoreVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPhoneticScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhoneticScore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPhoneticScoreVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhoneticScoreVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrthoScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrthoScore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrthoScoreVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrthoScoreVal As Global.System.Web.UI.WebControls.Label
End Class
