'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

    '''<summary>
    '''settingsForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents settingsForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''trackingHeaderControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trackingHeaderControl As Global.PPC.TrackingHeader

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lnkChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkChangePassword As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkUpdateEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkUpdateEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''advancedSettingsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents advancedSettingsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''userAdminLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userAdminLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkChangePswrdPolicy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkChangePswrdPolicy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''adminList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkDBMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDBMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkModifyDSNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkModifyDSNames As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkDeleteDrugName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDeleteDrugName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkViewSEDrugNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkViewSEDrugNames As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
