'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class WatchList

    '''<summary>
    '''WatchListForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WatchListForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Trackingheader2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Trackingheader2 As Global.PPC.TrackingHeader

    '''<summary>
    '''WatchListTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WatchListTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLWatchLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLWatchLists As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PrintScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintScreen As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SeperatorPipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeperatorPipe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DownloadScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadScreen As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''WatchlistType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WatchlistType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FDAGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FDAGrid1 As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''WatchListComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WatchListComments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DDMACComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDMACComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDMACAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDMACAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DDMacError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDMacError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''WatchListCommentsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WatchListCommentsLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DDMacCommentsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDMacCommentsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''WatchListHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WatchListHistory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HistoryErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HistoryErrorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FDAGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FDAGrid2 As Global.PPC.FDA.Controls.FDAGrid
End Class
