'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class NewSearchResults

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''TrackingHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrackingHeader1 As Global.PPC.TrackingHeader

    '''<summary>
    '''SearchText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAddWatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddWatch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MergedMatchLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MergedMatchLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MergedGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MergedGrid As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''MergedNotFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MergedNotFound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrthoMatchLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrthoMatchLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrthoGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrthoGrid As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''OrthoNotFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrthoNotFound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PhoneticMatchLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhoneticMatchLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PhoneticGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhoneticGrid As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''PhoneticNotFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhoneticNotFound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextMatchLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextMatchLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextGrid As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''TextNotFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextNotFound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddToWatchList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddToWatchList As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''SimpleSearchControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SimpleSearchControl1 As Global.PPC.SimpleSearchControl
End Class
