'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3634
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Settings

    '''<summary>
    '''settingsForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents settingsForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''trackingHeaderControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trackingHeaderControl As Global.PPC.TrackingHeader

    '''<summary>
    '''advancedSettingsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents advancedSettingsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''userAdminLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userAdminLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''adminList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
