'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Search

    '''<summary>
    '''frmSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSearch As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SearchHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchHeader As Global.PPC.TrackingHeader

    '''<summary>
    '''searchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSearchTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchTerm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addToWatchTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addToWatchTop As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''gridMergedHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridMergedSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedSearch As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridMergedMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMergedMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridPhoneticSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticSearch As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridPhoneticMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridPhoneticMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridOrthographicSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicSearch As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridOrthographicMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOrthographicMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridTextHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridTextSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextSearch As Global.PPC.FDA.Controls.FDAGrid

    '''<summary>
    '''gridTextMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridTextMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addToWatchBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addToWatchBottom As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''SearchResultsBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchResultsBox As Global.PPC.SearchBox

    '''<summary>
    '''searchRunning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchRunning As Global.System.Web.UI.WebControls.PlaceHolder
End Class
